root: true

env:
  node: true
  es6: true

extends:
  - plugin:vue/vue3-recommended
  - eslint:recommended
  - plugin:prettier/recommended
  - vue-global-api

ignorePatterns:
  - '**/dist/**'
  - '**/node_modules/**'
  - '.cache/**'
  - '.temp/**'
  - 'public/**'

overrides:
  - files:
      - '*.vue'

    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:prettier/recommended
      - '@vue/typescript/recommended'
      - '@vue/prettier'
      - '@vue/prettier/@typescript-eslint'

    plugins:
      - '@typescript-eslint'

    parser: vue-eslint-parser

    parserOptions:
      extraFileExtensions:
        - .vue
      parser: '@typescript-eslint/parser'

    rules:
      't@typescript-eslint/explicit-module-boundary-types':
        - off

      '@typescript-eslint/explicit-function-return-type':
        - off

      'no-undef':
        - warn

      '@typescript-eslint/naming-convention':
        - warn
        - selector: default
          format:
            - camelCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - variable
          format:
            - camelCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - property
          format:
            - camelCase
            - PascalCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: typeLike
          format:
            - PascalCase

      '@typescript-eslint/no-explicit-any':
        - warn
        - ignoreRestArgs: true

  - files:
      - '*.ts'

    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - plugin:prettier/recommended

    plugins:
      - '@typescript-eslint'

    parser: vue-eslint-parser

    parserOptions:
      parser: '@typescript-eslint/parser'
      project:
        - './tsconfig.json'
        - './tsconfig.eslint.json'

    rules:
      '@typescript-eslint/explicit-function-return-type':
        - off

      '@typescript-eslint/no-unsafe-member-access':
        - off

      '@typescript-eslint/no-unsafe-return':
        - off

      '@typescript-eslint/no-unsafe-call':
        - off

      '@typescript-eslint/no-unsafe-assignment':
        - off

      '@typescript-eslint/restrict-template-expressions':
        - off

      '@typescript-eslint/require-await':
        - off

      '@typescript-eslint/no-var-requires':
        - warn

      '@typescript-eslint/no-floating-promises':
        - warn

      'no-unused-vars':
        - error
        - { varsIgnorePattern: '.*', args: 'none' }

      '@typescript-eslint/no-misused-promises': off

      '@typescript-eslint/naming-convention':
        - warn
        - selector: default
          format:
            - camelCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - variable
          format:
            - camelCase
            - PascalCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - parameter
          format:
            - camelCase
            - PascalCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - property
          format:
            - camelCase
            - PascalCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: typeLike
          format:
            - PascalCase

      '@typescript-eslint/no-explicit-any':
        - warn
        - ignoreRestArgs: true

  - files:
      - '*.d.ts'
    rules:
      no-underscore-dangle:
        - off

  - files:
      - '**/__tests__/**/*.spec.{j,t}s?(x)'

    env:
      jest: true

    rules:
      '@typescript-eslint/no-explicit-any':
        - off
      '@typescript-eslint/no-unsafe-call':
        - off
      '@typescript-eslint/no-unsafe-assignment':
        - off
      '@typescript-eslint/no-unsafe-member-access':
        - off
